NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_R = 0.53
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_G = 0.34
NDefines.NGraphics.BORDER_COLOR_SELECTION_STATE_B = 0.63
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_R = 0.2
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_G = 0.098
NDefines.NGraphics.BORDER_COLOR_SELECTION_PROVINCE_B = 0.31